### ISSUE TITLE
MenuProcessor is missing "data" 

### ISSUE THREAD

**Issue by subjacked** [TYPO3-Initiatives/headless#112]
I needed sys_categories in my menu, so I tried to attach them to the MenuProcessor. The Problem is, that the MenuProcessor has no data object which passes the required fields back.

             ` menu = TEXT
                menu {
                    dataProcessing {
                        10 = FriendsOfTYPO3\Headless\DataProcessing\MenuProcessor 
                        10 {
                            special = list
                            special.value.field = pages
                            as = menu
                            dataProcessing {
                                10 = FriendsOfTYPO3\Headless\DataProcessing\FilesProcessor
                                10 {
                                    references.fieldName = menu_image
                                    as = image
                                    processingConfiguration.height = {$projects.image.height}
                                    processingConfiguration.width = {$projects.image.width}
                                }
                                20 = TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor
                                20 {
                                    as = categories
                                    selectFields = sys_category.title
                                    table = sys_category
                                    pidInList = root,-1
                                    where = sys_category_record_mm.uid_foreign = {field:uid}
                                    where.insertData = 1
                                    leftjoin = sys_category_record_mm ON sys_category_record_mm.uid_local = sys_category.uid
                                }
                            }
                        }
                    }
                }`

**Comment by lukaszuznanski** [comment]
You can use core MenuProcessor

**Comment by lukaszuznanski** [comment]
Related to #121

**Comment by lukaszuznanski** [comment]
@twoldanski is working on issue
