### ISSUE TITLE
Capability to customize the FriendsOfTYPO3\MenuProcessor TypoScript configuration

### ISSUE THREAD

**Issue by Moongazer** [TYPO3-Initiatives/headless#116]
Unfortunately it seems not possible to customize the TypoScript configuration of `FriendsOfTYPO3\MenuProcessor` e.g. to append a new field `"id":` to the response. I need a unique value for each menu entry... and using the `link` value is hard to deal with because of type string.

Just out of curiosity I was trying this, but I guess this is not how the dataProcessing works in general^^ 
```
lib.primaryNavigation {
  dataProcessing {
    10 {
      stdWrap.cObject.100 = TEXT
      stdWrap.cObject.100 {
        field = uid
        wrap = "id":|
      }
    }
  }
}
```

**Comment by lukaszuznanski** [comment]
Hi,

I think that stdWrap is not supported on top level by MenuProcessor, but you can run stdWrap on any configuration value. In your example, you don't set dataProcessing 10 to MenuProcessor. I will check if it's possible to run/add stdWrap on top level

**Comment by Moongazer** [comment]
> I think that stdWrap is not supported on top level by MenuProcessor, but you can run stdWrap on any configuration value.
You're right, its throws an exception, but I just wanted to try where the `$menuLevelConfig` from the MenuProcessor goes to (I'm not familiar how the DataProcessors working under the hood yet).
What do you mean by "you can run stdWrap on any configuration value"? Please let us know if you find a way, thanks :)
