### ISSUE TITLE
[FEATURE] Using felogin authentication over headless API

### ISSUE THREAD

**Issue by Moongazer** [TYPO3-Initiatives/headless#119]
Not sure if this is possible already out of the box, can you as developer say something to this? If it's not possible, this would be a good feature-resquest as the user management is one of the strength of TYPO3 over other systems in my opinion, which should work especially in web-apps.

**Comment by lukaszuznanski** [comment]
Hi,

actually, we are working on felogin implementation. We will probably talk about this and work with on upcoming codesprint https://typo3.org/event/20200616-typo3-headless-pwa-codesprint-online

**Comment by Moongazer** [comment]
Thank you, I will join and see if I might be able to contribute something. The last days I was trying to make the headless API more dynamic (to make it a two-way instead of a oneway API), to have endpoints to interact with or send requests to (e.g. for dynamic content-elements, like polls or votings). All tryouts failed so far, I guess I've to see what comes with the EXT:form support feature. Maybe the felogin goes into a similar direction.

**Comment by lukaszuznanski** [comment]
We have prepared support for ext:form, but atm it's limited to one step in form, so I will work on this during codesprint and push it :).

I guess, felogin integration is not going to be hard, send url and properties in json to frontend for proper handling of request, we'll see, it's on list for codesprint.
