### ISSUE TITLE
Add version tag to Github and/or add branch-alias to composer.json

### ISSUE THREAD

**Issue by schloram** [TYPO3-Initiatives/headless#12]
Hi guys, 
sorry for opening so many issues. 🙈

Would it be possible to add a tag to the repo so we don’t have to checkout `dev-master`? Alternatively (or additionally 🙂) the `branch-alias` functionality of composer.json could be used.

for example: 
```
"extra": {
    "branch-alias": {
      "dev-master": "1.0.x-dev"
    }
  }
```
So we could simply use `^1.0` in our own projects composer.json and don’t have to bother changing the version when v1.0 is finally released/a tag is created.

best,
Ramón

**Comment by tmotyl** [comment]
Here you go: https://github.com/TYPO3-Initiatives/headless/releases/tag/v1.0.0

**Comment by schloram** [comment]
Great! Thanks.
