### ISSUE TITLE
[TASK] MenuProcessor/LanguageMenuProcessor performance

### ISSUE THREAD

**Issue by lukaszuznanski** [TYPO3-Initiatives/headless#128]
Menu processor and Language menu processor is struggling with a lot of languages and pages, we have performance issues, this should be addressed and profiled.

**Comment by theLine** [comment]
The performance of `HMENU` is really bad and `ACT` and `CUR` states won't be cached at all.
I've used [EXT:menus (b13/menus)](https://github.com/b13/menus) in the past with remarkable performance.
Maybe it's possible to adapt some behaviour from EXT:menus into this (or use it as a replacement for `HMENU`)
