### ISSUE TITLE
Wrong MenuProcessor in MenuAbstract.typoscript

### ISSUE THREAD

**Issue by schloram** [TYPO3-Initiatives/headless#13]
Hi,
the MenuProcessor used in `Configuration/TypoScript/ContentElement/MenuPages.typoscript` is `TYPO3\CMS\Frontend\DataProcessing\MenuProcessor`. But this outputs every single DB column of the page. This should probably be `FriendsOfTYPO3\Headless\DataProcessing\MenuProcessor` (like in the other menu content elements) to limit the fields that are displayed in the json.

But when changing the namespace the chained FilesProcessor is throwing an exception.

**Comment by lukaszuznanski** [comment]
Yea, that's because FilesProcessor uses `data` to resolve relation, which is removed by FriendsOfTYPO3\Headless\DataProcessing\MenuProcessor.

**Comment by schloram** [comment]
I see. I will think about a solution then. 🤔

**Comment by lukaszuznanski** [comment]
Solved by #152
