### ISSUE TITLE
[TASK] Create part of documentation for integrating external plugin

### ISSUE THREAD

**Issue by lukaszuznanski** [TYPO3-Initiatives/headless#138]

**Comment by Moongazer** [comment]
What exactly to you mean by external plugins? Should it be a description of how to work with news (through headless_news) and how to setup the felogin? Because headless_news is an extension itself it will have an own documentation I guess... so not sure what this chapter is about

**Comment by lukaszuznanski** [comment]
Hi,

I mean how can you integrate third party extensions (based on fluid) such as ext:news. We need to document how user can integrate any external plugin, for example user uses extension foo based on extbase and fluid and how user can migrate this extension to use it via headless.

Headless news is preferred example of third party plugin integration into headless.

**Comment by Moongazer** [comment]
Ah ok, so I can headless_news as an example. I guess we need to explain also the JSON rendering through template files and that stuff right?
