### ISSUE TITLE
Add json fields

### ISSUE THREAD

**Issue by schloram** [TYPO3-Initiatives/headless#14]
Hi,
there are some fields that are missing in my opinion.

In "lib.page":
- `files` (array of objects): The files added to a page in "Resources -> Files"
- `socialMedia` (object): The fields `og_title`, `og_description`, `twitter_title`, `twitter_description`, `twitter_image` combined.
- `noSearch` (bool): The output of the field "Include in Search"
- `categories` (array of objects): The categories the page is assigned to.

In "lib.contentElement":
- `categories` (array of objects): The categories the content element is assigned to.

Is there a reason that these fields are missing or do you think they can be added as well? Because I think they are important for the frontend rendering.

**Comment by lukaszuznanski** [comment]
Hi,
yes, those fields should be added. There is no extra reason, we just forgot about them, as we don't use them atm.

**Comment by schloram** [comment]
Thanks for your super fast response. :)

I will add them in a PR soon.

best,
R
