### ISSUE TITLE
The content element "Related pages" (menu_related_pages) is empty

### ISSUE THREAD

**Issue by Moongazer** [TYPO3-Initiatives/headless#147]
The `content.menu` JSON array is empty for content element "Related pages" (menu_related_pages), even if there are some pages given in "Selected Pages".

**Comment by sabbelasichon** [comment]
@Moongazer Are you sure? I think the concept of related pages is maybe a hidden gem of TYPO3. Check out this: https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Hmenu/Index.html#special-keywords

**Comment by lukaszuznanski** [comment]
Closing, as it's core feature.

**Comment by Moongazer** [comment]
> @Moongazer Are you sure?
Ah sorry, didn't know that it looks for related pages based on keywords, the input form for the "Selected Pages" was missleading me as this should not be there than by core^^ (Or does it has another functionality in this context?!)

**Comment by sabbelasichon** [comment]
@Moongazer You have to define the pages you want to look up. So it makes totally sense to have this pages field there. IMHO
