### ISSUE TITLE
Each page the same json-content?

### ISSUE THREAD

**Issue by gkaplick** [TYPO3-Initiatives/headless#20]
Today i was testing the headless-extension but i failed at the very beginning...

Each page i call up, shows the same json-content (only navigation)
`[{"data":{"uid":83,"pid":1,"tstamp":1571222872,"crdate":1571222872,"cruser_id":1,"deleted":0,"hidden":0,"starttime":0,"endtime":0,"fe_group":"","sorting":0,"rowDescription":null,"editlock":0,"sys_language_uid":0,"l10n_parent":0,"l10n_source":0,"l10n_state":null,"t3_origuid":0,"l10n_diffsource":"a:1:{s:8:\"shortcut\";N;}","t3ver_oid":0,"t3ver_id":0,"t3ver_label":"","t3ver_wsid":0,"t3ver_state":0,"t3ver_stage":0,"t3ver_count":0,"t3ver_tstamp":0,"t3ver_move_id":0,"perms_userid":1,"perms_groupid":1,"perms_user":31,"perms_group":27,"perms_everybody":0,"title":"Home","slug":"\/home","doktype":4,"TSconfig":"","is_siteroot":0,"php_tree_stop":0,"url":"","shortcut":1,"shortcut_mode":0,"subtitle":"","layout":0,"target":"","media":0,"lastUpdated":0,"keywords":"","cache_timeout":0,"cache_tags":"","newUntil":0,"description":"","no_search":0,"SYS_LASTCHANGED":0,"abstract":"","module":"","extendToSubpages":0,"author":"","author_email":"","nav_title":"","nav_hide":0,"content_from_pid":0,"mount_pid":0,"mount_pid_ol":0,"alias":"","l18n_cfg":0,"fe_login_mode":0,"backend_layout":"","backend_layout_next_level":"","tsconfig_includes":"","legacy_overlay_uid":0,"tx_impexp_origuid":54,"seo_title":"","no_index":0,"no_follow":0,"og_title":"","og_description":null,"og_image":0,"twitter_title":"","twitter_description":null,"twitter_image":0,"canonical_link":"","categories":0,"nav_icon":0,"thumbnail":0,"isSpacer":false},"title":"Home","link":"\/","target":"","active":0,"current":0,"spacer":0,"icon":[]},{"data":{"uid":82,"pid":1,"tstamp":1571222872,"crdate":1571222872,"cruser_id":1,"deleted":0,"hidden":0,"starttime":0,"endtime":0,"fe_group":"","sorting":1,"rowDescription":null,"editlock":0,"sys_language_uid":0,"l10n_parent":0,"l10n_source":0,"l10n_state":null,"t3_origuid":0,"l10n_diffsource":"a:1:{s:6:\"hidden\";N;}","t3ver_oid":0,"t3ver_id":0,"t3ver_label":"","t3ver_wsid":0,"t3ver_state":0,"t3ver_stage":0,"t3ver_count":0,"t3ver_tstamp":0,"t3ver_move_id":0,"perms_userid":1,"perms_groupid":1,"perms_user":31,"perms_group":31,"perms_everybody":0,"title":"Spacer","slug":"\/spacer","doktype":199,"TSconfig":null,"is_siteroot":0,"php_tree_stop":0,"url":"","shortcut":0,"shortcut_mode":0,"subtitle":"","layout":0,"target":"","media":0,"lastUpdated":0,"keywords":null,"cache_timeout":0,"cache_tags":"","newUntil":0,"description":null,"no_search":0,"SYS_LASTCHANGED":0,"abstract":null,"module":"","extendToSubpages":0,"author":"","author_email":"","nav_title":"","nav_hide":0,"content_from_pid":0, {...}`

can anybody tell me, what i'm doin wrong?

kind regards / thx

**Comment by tgrzemski** [comment]
If you are on T3Con come to our booth and we will check :)

**Comment by gkaplick** [comment]
hm, sry... not a really helpful option :/so... do i have to use parameters to get the content? should the api deliver already content? currently there is just an navigation-part...
null

**Comment by snador1977** [comment]
I try to specify the question again. We have not found any info / documentation. When I call the root Url www.t3example.de, I get the Json output of the Typo3 main page with all the resources. Is there a way to call the JSON data for www.t3example.de/page or www.t3example.de/page/page. What is the standardized way to retrieve the data of a single page? As I have described it? Or do I have to retrieve a special URL to get the data of a single page?

**Comment by lukaszuznanski** [comment]
Ok, what version of TYPO3 are you using?

I just setup clean TYPO3 9.5 page, installed extension and got it working right away. You access other pages like standard TYPO3 pages. So if you have page with slug 'foo', you go to yourdomain.com/foo and you should have your JSON output of page. 

Are you trying to use this extension on already existing webpage, or new instance of TYPO3? Please provide more information.

**Comment by lukaszuznanski** [comment]
Please show me also your full typoscript includes in page you want to access.

**Comment by lukaszuznanski** [comment]
You should install extension, include typoscript template (for rendering) and you don't need to write anything on your own, to get it working. Basic TYPO3 content elements and page data should be available straight away, without any additional configuration. Examples in Readme are just for writing custom content elements and fetching additional page data.

**Comment by Smove** [comment]
We installed the extension in a composer based 9.5.10 project. Only the Introduction Package with the standard content is running. The TypoScript template was included after the one from the Bootstrap Package.

It seems as if only the navigation is output. The numType for the menu, however, generates a different output.

![image](https://user-images.githubusercontent.com/3686891/67178355-b06b1400-f3d2-11e9-8992-d87430d470ae.png)

![image](https://user-images.githubusercontent.com/3686891/67178364-b9f47c00-f3d2-11e9-9ff0-cc963ca55b9c.png)

**Comment by tmotyl** [comment]
@Smove you can't have Headless and bootstrap packege on the same site. 
Remove all static TS templates and just include headless.

**Comment by Smove** [comment]
@tmotyl Thanks. Seems working now.
