### ISSUE TITLE
ext:form throws error if headless is enabled, but not included in the root template

### ISSUE THREAD

**Issue by wayheyha** [TYPO3-Initiatives/headless#218]
**Error-Message:** 
Error handler | Core: Exception handler (WEB):  Uncaught TYPO3 Exception: Argument 1 passed to  TYPO3\CMS\Form\Domain\Model\FormDefinition::__construct() must be of the  type string, null given, called in  /dev01/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php  on line 3431 \| TypeError thrown in file  /dev01/public/typo3/sysext/form/Classes/Domain/Model/FormDefinition.php  in line 311.

**Setup:** 
TYPO3 10 LTS, Headless 2.3.0

**Description:**
I have two root pages:
- one for my site, where headless is not included in the template
- one for the headless api as descriped in the documentation

If i have the headless-extension activated, and open a page under a the root page where headless is not included and a form is placed, the error-message above is thrown. 

If i disable ext-headless int the extension manager no error is thrown.

I used the ext:form example form. 

Best regards,
Chris

**Comment by twoldanski** [comment]
Hello @wayheyha 
I reproduced issue with fluid (one site) & headless (in another site) in one instance. 
I created small patch(https://github.com/TYPO3-Initiatives/headless/pull/219/files) which should resolve your issue. 
In my tests, in both cases (fluid & headless) with this patch forms work as should. 
Please let us know if issue mitigated when patch is applied in your setup. 
 
Thank you for reporting !

**Comment by wayheyha** [comment]
Hello @twoldanski,

your fix works for me :-) 

Thank you very very much for your excellent extension and for you quick response!!
