### ISSUE TITLE
EXT:form problems in mixed mode (normal/headless)

### ISSUE THREAD

**Issue by rasgor** [TYPO3-Initiatives/headless#229]
I'am running a TYPO3 instance in normal and headless mode with 2 entry points (site configs). One should server the website an the other should be used building an API. I have experienced problems in normal mode (website) with the form framework when EXT:headless ist loaded. E.g. if I preselect a form persistenceIdentifier in the TYPO3 Backend for website usage the frontend gives me following error:

![image](https://user-images.githubusercontent.com/22767023/105016107-8a537a00-5a42-11eb-99bd-dd4c3e63dee9.png)

Current system: TYPO3 10.4.12 and EXT:headless 2.3.0

**Comment by lukaszuznanski** [comment]
Hi,

@rasgor could you try to use current master branch of headless? If it works correctly, then I will release 2.3.1 with fix.

**Comment by rasgor** [comment]
@lukaszuznanski  Thx for your quick response and solution. I've done a composer update with  `"friendsoftypo3/headless": "dev-master"` . The problem is gone.

**Comment by lukaszuznanski** [comment]
Great, then I will create 2.3.1 bugfix release.

**Comment by rasgor** [comment]
Fine. Thank you.

**Comment by lukaszuznanski** [comment]
@rasgor fixed in 2.4.0 release :) closing this issue, please reopen if you have any further questions
