### ISSUE TITLE
FlexFormProcessor and additional Processing with typolink, etc.

### ISSUE THREAD

**Issue by kledo-34** [TYPO3-Initiatives/headless#239]
Hey there,
thank you for the great extension. Is it possible to process a field with the FlexFormProcessor and then process a field in the as output array with e.g. typolink? I can't get the correct configuration for this, if it is possible it would be great if you could provide an example.
Thanks a lot.

**Comment by Moongazer** [comment]
Its possible with TypoScript by default, no need to open a ticket here. Just create a nested structure with your desired DataProcessors, there are plenty examples around (or look in other extensions). E.g.:
```
example = TEXT
example {
    dataProcessing {
        10 = TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor
        10 {
            # ...
            dataProcessing {
                10 = MyVendor\MyExtension\DataProcessor\CustomDataProcessor
                10 {
                    # ...
                }
            }
        }
    }
}
```

**Comment by lukaszuznanski** [comment]
Hi,
if your issue is not resolved by nesting DataProcessors, please reopen.
