### ISSUE TITLE
[FEATURE] Add option to configure front-end domain for "Preview page" button

### ISSUE THREAD

**Issue by lukaszuznanski** [TYPO3-Initiatives/headless#27]

**Comment by lukaszuznanski** [comment]
Actually, I would like to add this option in site configuration, but currently I'm unable to create inline relation in Site configuration, because it's not allowed, so it's not possible to change preview domain during deployment.

**Comment by meincms** [comment]
@lukaszuznanski how about to just use the typo3 settings in:
siteconfiguration > edit current site (hit the edit icon) > first tab > entrypoint > add the domain. 
as long as the page you intend to preview is hidden, you won't be able to preview this certain site, but for all the other pages this workaround does its job quite well for me.

**Comment by lukaszuznanski** [comment]
Hi @meincms,

Ok, but what about environments. I have like 3 different domains based on environment, so on test environment I already specified domain, and when I add another one, nothing really changes, because TYPO3 takes first one. Maybe I'm missing something?

**Comment by lukaszuznanski** [comment]
Solved in #106
