### ISSUE TITLE
[Suggestion] add `require: { "typo3/cms-redirects": "^9.5 || ^10.0" }` to composer.json

### ISSUE THREAD

**Issue by rowild** [TYPO3-Initiatives/headless#275]
Since it is possible to setup TYPO3 with only selected extensions, it might be the case that `cms-redirect` is missing. This, however, causes TYPO3 to break completely, when headless gets installed. Therefore it would be of help to add it to the list if required extensions.

What do you think?

**Comment by lukaszuznanski** [comment]
Hi,

I think we should fix issue that breaks TYPO3 if ext:redirects is not installed instead of adding this extension as dependency as it should not be required to run headless extension at all. Thanks for your input, as I was unaware that we have bug :).

**Comment by twoldanski** [comment]
Hi @rowild, 
could you provide example for your setup & more details how not installed `ext:redirect` with headless causes TYPO3 to crash? 
Redirect support for headless is behind `headless.redirectMiddlewares` flag, off by default

**Comment by rowild** [comment]
HI @twoldanski!

I just repeated my install routine several times, without `ext:redirect`. And - as always in such cases - everything works fine. I am not sure what I could have done wrong in the first run, but it was obviously sth different than this. If I find out more details that are more bullet-proof, I will come back and reopen this issue.

Sorry for the false alarm!
Looking forward to work with your headless solutions! Very much indeed! :-)
