### ISSUE TITLE
[QUESTION] Hook into TypoLink's returnLast = url

### ISSUE THREAD

**Issue by kitzberger** [TYPO3-Initiatives/headless#304]
Due to a hook into the processing of typolinks the result is being overwritten for `returnLast = url` with a JSON object. See https://github.com/TYPO3-Initiatives/headless/blob/master/Classes/Hooks/TypolinkHook.php#L88

IMHO, that's a non ideal solution, e.g. there's cases
* when I'm only interested in the URL itself (and not target and other params!)
* when I want to further process the URL via TypoScript (e.g. apply a `wrap` to it)

Why not implement a new option `returnLast = json` that returns the JSON object and let `returnLast = url` as it is?

**Comment by tmotyl** [comment]
related: 
https://review.typo3.org/c/Packages/TYPO3.CMS/+/70590

**Comment by lukaszuznanski** [comment]
@kitzberger let me know if this https://github.com/TYPO3-Initiatives/headless/commit/e03f85f7bb3aaa0ba9c0a64fab125fb0b6a23f36 solves your issue and we can close it.
