### ISSUE TITLE
Allow FLOAT as cObject type

### ISSUE THREAD

**Issue by lochmueller** [TYPO3-Initiatives/headless#381]
Hey everyone,

would be cool to create a FLOAT cObject type for casting in the right type in the JSON. Currently it is hard to implement by myself, because the casting is partof the final JSON Object Class: https://github.com/TYPO3-Initiatives/headless/blob/master/Classes/ContentObject/JsonContentObject.php#L107

I suggest create a new Content Object for FLOAT and add also the casting in the JsonContentObject.

One more note: Using final in classes destroy the TYPO3 core mechanisms to override classes. Perhaps also drop the "final" in the classes?

Regards,
Tim

**Comment by lukaszuznanski** [comment]
Hi,

thanks for your input. I think we can consider creating FLOAT cObj. I agree with you, we should drop `final`.
