### ISSUE TITLE
Add extension to packagist

### ISSUE THREAD

**Issue by schloram** [TYPO3-Initiatives/headless#4]
Hi everybody,
good work on the extension! :) Thanks for it.

But to make it easier to install the extension via composer it should be added to packagist. 
Otherwise the extension can only be installed when the repo is added to the `repositories` array in `composer.json`.

Also a proper version tag should be added to the repo so we don't have to use `dev-master` when installing.

See error when installing it as discribed in the README:
```
Could not find a matching version of package friendsoftypo3/headless. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable)
```

best,
R

**Comment by tmotyl** [comment]
working on it :)

**Comment by schloram** [comment]
Great! Thanks for your very quick response.

**Comment by tmotyl** [comment]
here you go https://packagist.org/packages/friendsoftypo3/headless
