### ISSUE TITLE
No Navpoint IDs on http://www.domain.de/?type=834

### ISSUE THREAD

**Issue by snador1977** [TYPO3-Initiatives/headless#62]
Would not it be an advantage if the unique ids of the navigation points in the JSON output were also output when retrieving the navigation (http://www.domain.de/?type=834)? Or do we have a bug?

**Comment by lukaszuznanski** [comment]
Can you provide your output from ?type=834 ?

**Comment by lukaszuznanski** [comment]
Also, please pull current master and check again, I changed menu configuration slightly in https://github.com/TYPO3-Initiatives/headless/pull/63.

**Comment by snador1977** [comment]
> Können Sie die Ausgabe von? Type = 834 bereitstellen?

Unique NAV is missing...

Example:
`"navigation": [
        {
          "title": "Home",
          "link": "/",
          "target": "",
          "active": 0,
          "current": 0,
          "spacer": 0
        },
        {
          "title": "Features",
          "link": "/features",
          "target": "",
          "active": 0,
          "current": 0,
          "spacer": 0
        },
        {
          "title": "Customize",
          "link": "/customize",
          "target": "",
          "active": 0,
          "current": 0,
          "spacer": 0
        },
        {
          "title": "Pages",
          "link": "/pages",
          "target": "",
          "active": 0,
          "current": 0,
          "spacer": 0,
          "children": [
            {`

**Comment by snador1977** [comment]
> Also, please pull current master and check again, I changed menu configuration slightly in #63.

We check this...

**Comment by lukaszuznanski** [comment]
Ok, so I guess you want to have some unique identifier for each field in navigation? You can write your own typoscript custom menu if you want, just add them to output. I will send you snippet with menu which provides identifier.

**Comment by lukaszuznanski** [comment]
If you have any other questions, please open new issue.
