### ISSUE TITLE
Typoscript for Shortcut seems to be invalid

### ISSUE THREAD

**Issue by sven-carstens** [TYPO3-Initiatives/headless#86]
After having troubles to add typoscript after headless was included I drilled it down to line #14 in Configuration/TypoScript/ContentElement/Shortcut.typoscript.

If I put it into anything conditional the BE complains about a missing brace. All following typoscript will land at unintended places.

Screenshot is attached to show the place where the error seems to be. (#2490 in that case)

styles.content.shortcut.tables is set to tt_content

![image](https://user-images.githubusercontent.com/7496761/70221721-26d89100-1749-11ea-8fe9-d159c123f6c5.png)

**Comment by sven-carstens** [comment]
Proposed fix works for me.

**Comment by tmotyl** [comment]
merged
