### ISSUE TITLE
[FEATURE] Add non-cached plugin INT_SCRIPT handling

### ISSUE THREAD

**Issue by lukaszuznanski** [TYPO3-Initiatives/headless#89]
Find way to output non-cached plugin data. We can use typoscript rendering extension, but we want to solve this without additional prerequisites. Problem is that INT_SCRIPT is hardcoded in ContentObjectRenderer to have max 32 characters, but JsonContentObject wrap INT_SCRIPT in " ", so it's 34 character long. We can also hook into ContentObjectRenderer and clean INT_SCRIPT.

**Comment by sven-carstens** [comment]
Possible content from a tt_content record headless might be:

1. long string with INT_SCRIPT somewhere inside
INT_SCRIPT replacing by standard means will fail if there are charactes which must be escaped for JSON output, so we need special case custom replacement which escapes the replacement before inserting it into the output

2. single string which only consists of the INT_SCRIPT placeholder. (eg. none-cacheable extbase action)
 Here are some possible scenarios:
- replace with URL to let the FE load the proper content
- special output handling which escapes the content or if the content is valid JSON it should be placed into the output without special quotes

**Comment by lukaszuznanski** [comment]
@sven-carstens 
looks like your solution works just fine for me, and I think it's better approach than my implementation, we can work with this.

**Comment by sven-carstens** [comment]
It might break if we add more features to nest JSON output.
If we have a nesting of JSON-CO -> COA_INT -> JSON-CO -> COA_INT it will double json_encode the inner most content. But I think this is not possible to trigger with the current setup.
